from tkinter import *


class AppConstants:

    yellow_color = "#FFD379"
    main_color = "#89DAD0"
    light_orange = "#FCAB88"
    amber_accent = "#FFBF00"
    cream = "#F3EEEA"
    logo_add = "logo.png"
    text_logo_add = "assets/text_logo.png"
    key_add = "assets/key.png"
    exit_small_button_add = "assets/exit_small_button.png"
    login_button_add = "assets/login_button.png"
    chng_pass_add = "assets/chng_pass_button.png"
    login_backgnd_add = "assets/login_backgnd.png"
    answers_button_add = "assets/answers_button.png"
    change_pass_backgnd_add = "assets/chg_pass_backgnd.png"
    enter_button_add = "assets/enter_button.png"
    cancel_button_add = "assets/cancel_button.png"
    start_button_add = "assets/start_button.png"
    profile_backgnd_add = "assets/profile_backgnd.png"
    questions_backgnd_add = "assets/Q_backgrounds.png"
    next_q_button_add = "assets/next_q.png"
    prev_q_button_add = "assets/prev_q.png"
    exit_large_button_add = "assets/exit_large_button.png"
    no_image_add = "assets/no_image.png"
    finish_button_add = "assets/finish_button.png"
    key_backgnd_add = "assets/key_backgnd.png"
    reult_backgnd_add = "assets/result_backgnd.png"
    excellent_emoji_add = "assets/excellent_emoji.png"
    good_emoji_add = "assets/good_emoji.png"
    bad_emoji_add = "assets/bad_emoji.png"
    oops_emoji_add = "assets/oops_emoji.png"
